---
- name: Pre-scaleup hostfile checks
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - import_role:
        name: openshift_node
        tasks_from: scaleup_checks.yml

- name: Pre-scaleup checks
  hosts: new_workers
  tasks:
    - import_role:
        name: openshift_node
        tasks_from: version_checks.yml

- name: install nodes
  hosts: new_workers
  roles:
    - openshift_node
